src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>EngineeringReqNumber__c</fullName>
        <label>Engineering Req Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <description>Fase del proceso de negocio en la que se encuentra el registro</description>
        <inlineHelpText>Fase del proceso de negocio en la que se encuentra el registro</inlineHelpText>
        <label>Phase</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PotentialLiability__c</fullName>
        <label>Potential Liability</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GC1040</fullName>
                </value>
                <value>
                    <fullName>GC1060</fullName>
                </value>
                <value>
                    <fullName>GC3020</fullName>
                </value>
                <value>
                    <fullName>GC3040</fullName>
                </value>
                <value>
                    <fullName>GC3060</fullName>
                </value>
                <value>
                    <fullName>GC5020</fullName>
                </value>
                <value>
                    <fullName>GC5040</fullName>
                </value>
                <value>
                    <fullName>GC5060</fullName>
                </value>
                <value>
                    <fullName>GC1020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLAViolation__c</fullName>
        <label>SLA Violation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Case_Phase__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Phases</relationshipLabel>
        <relationshipName>Case_Phases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Full_Result__c</fullName>
        <label>Full Result</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                    <default>true</default>
                    <label>Valid</label>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Phase</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Case Phase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CalculationsCaseWS.cls
global class CalculationsCaseWS {
	
	global class CalculationsCaseResut {
		webservice String analyzeResult { get; set; }
		webservice String caseId {get; set;}
		webservice Boolean error {get; set;}
		webservice String returnCode {get; set;}
		webservice String errorMessage {get; set;}
	}

	public CalculationsCaseWS() {
		
	}

	webservice static String caseCalculationsResult(CalculationsCaseResut result) {
		System.debug(JSON.serialize(result));
		Case c = [SELECT Id, CaseNumber, ContactId, AccountId, AssetId, ParentId, SuppliedName, SuppliedEmail, SuppliedPhone, SuppliedCompany, Type, Status, Reason, Origin, Subject, Priority, Description, IsClosed, ClosedDate, IsEscalated, OwnerId, LastViewedDate, LastReferencedDate, EngineeringReqNumber__c, SLAViolation__c, Product__c, PotentialLiability__c, Phase__c FROM Case where Id = :result.caseId];
		Case_Phase__c ph = new Case_Phase__c(Case__c = c.Id,
		                                     Phase__c = c.Phase__c,
		                                     Status__c = !result.error ? 'Valid' : 'Error',
		                                     Result__c = result.analyzeResult.abbreviate(Schema.SObjectType.Case_Phase__c.fields.Result__c.getLength()),
		                                     Full_Result__c = result.analyzeResult.abbreviate(Schema.SObjectType.Case_Phase__c.fields.Full_Result__c.getLength())
		                                    );
		insert ph;
		if (ph.Status__c == 'Valid') {
			update new Case(Id = c.Id, Phase__c = 'SaveResults');
		}
		return 'done';
	}
}