src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>EngineeringReqNumber__c</fullName>
        <label>Engineering Req Number</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <description>Fase del proceso de negocio en la que se encuentra el registro</description>
        <inlineHelpText>Fase del proceso de negocio en la que se encuentra el registro</inlineHelpText>
        <label>Phase</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PotentialLiability__c</fullName>
        <label>Potential Liability</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GC1040</fullName>
                </value>
                <value>
                    <fullName>GC1060</fullName>
                </value>
                <value>
                    <fullName>GC3020</fullName>
                </value>
                <value>
                    <fullName>GC3040</fullName>
                </value>
                <value>
                    <fullName>GC3060</fullName>
                </value>
                <value>
                    <fullName>GC5020</fullName>
                </value>
                <value>
                    <fullName>GC5040</fullName>
                </value>
                <value>
                    <fullName>GC5060</fullName>
                </value>
                <value>
                    <fullName>GC1020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLAViolation__c</fullName>
        <label>SLA Violation</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Case_Phase__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Phases</relationshipLabel>
        <relationshipName>Case_Phases</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Full_Result__c</fullName>
        <label>Full Result</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Phase</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Case Phase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ValidationsCaseQueueable.cls
public with sharing class ValidationsCaseQueueable extends AbstractQueueable {
	private Case c;
	public transient String result;

	public ValidationsCaseQueueable(Case c) {
		this.c = c;
	}
	public override void executeJob(System.QueueableContext context) {
		try {
			c = [SELECT Id, CaseNumber, ContactId, AccountId, AssetId, ParentId, SuppliedName, SuppliedEmail,
			     SuppliedPhone, SuppliedCompany, Type, Status, Reason, Origin, Subject, Priority,
			     Description, IsClosed, ClosedDate, IsEscalated, OwnerId, ContactPhone, ContactMobile,
			     ContactEmail, ContactFax, LastViewedDate, LastReferencedDate, EngineeringReqNumber__c,
			     SLAViolation__c, Product__c, PotentialLiability__c, Phase__c
			     FROM Case where Id = :c.Id];
			LegacyValidations.LegacyPortType validationService = new LegacyValidations.LegacyPortType();
			result = validationService.LegacyValidations(c.Id, JSON.serialize(c));
			Case_Phase__c ph = new Case_Phase__c(Case__c = c.Id,
			                                     Phase__c = c.Phase__c,
			                                     Result__c = result.abbreviate(Schema.SObjectType.Case_Phase__c.fields.Result__c.getLength()),
			                                     Full_Result__c = result.abbreviate(Schema.SObjectType.Case_Phase__c.fields.Full_Result__c.getLength())
			                                    );
			insert ph;
			update new Case(Id = c.Id, Phase__c = 'Calculations');
		} catch (CalloutException ex) {
			System.debug(ex.getStackTraceString());
			throw new ValidationsCaseException(ex.getMessage());
		}
	}

	public class ValidationsCaseException extends Exception {

	}
}